### ISSUE TITLE
Hey Thanks !

### ISSUE THREAD

**Issue by 3kynox** [minagawah/webpack-in-5min-vuejs#1]
Hello and thanks for this resources !

I was searching a way to have vue / vue router / vuex / webpack / gulp / and threejs integrated simply with a lot of comments and explanations (for my learning), looks like I've found it.

Some questions please : 

- Why not having used official webpack vue example ? -> https://github.com/vuejs-templates/webpack
- Not better to use official boilerplate ? (folder structure, good practices)
- Will you keep your repos updated ?
- Can you point me out which commits are related to threeJs integration ?
- Any way to bi-directional passing data between vue & three ?
- Any informations using a separated backend (like symfony or laravel) ?

Thanks again.

**Comment by minagawah** [comment]
```
> Why not having used official webpack vue example ? -> https://github.com/vuejs-templates/webpack
> Not better to use official boilerplate ? (folder structure, good practices)
```

Number of reasons. Firt of all, I wanted to make it as simple as possible so that I can easily customize in accord with whatever the new project requires, and also make it easy for my co-workers to understand what's going on. While the official template uses "Express" for development, we do not always want "Express", and so using *"webpack-dev-server"* for hot-reloads.  
Also, while the official template lets us create a new project using `.vue` extension files as default, I have many designers working together who prefer simple HTML over `.vue` files for templates, so using HTML files instead. Likewise, there are so many other settings and features that are commonly used in many of my actual projects.  
To list a few....  
I want common libraries such as "ThreeJS" to be always included, I want "stylus" as for the default CSS bundler, I want to easily handle `env` related variables, I want license information to be omitted from being uglified when bundling for productions, I have many common Vue component related codes prefered to be included as templates (such as *Vuex* related store management features) , etc.  
If I were to use the official template, I must copy and paste all of them whenever creating a new project, and that's too time consuming.

However, the biggest reason is that I want people (including me) to install all the npm modules by themselves.  
Notice, in README, I have a list of all the node modules installing. Not by doing `git clone` this project and typing `npm install` to create projects, I rather expect users to `npm install [whatever the modules prefered]` themselves to install a whole new set of npm modules for new projects instead, so that the newly created projects contains the most recent versions.
So, I basically want users not to utilize this project as a *template*, but a *reference* to easily setup their own Vue projects.

For the folder structures, yes... I should refer some ideas presented in the official template...

```
> Will you keep your repos updated ?
```

Yes, I realize that I haven't been updating this project for a long time.  
I guess I will work on it this weekend...

```
> Can you point me out which commits are related to threeJs integration ?
```

Importing ThreeJS is easy. However, the related modules are not...  
As you can see [in my sample program](https://github.com/minagawah/webpack-in-5min-vuejs/blob/master/src/routes/grid/grid.js#L12), it uses *imports-loader* and *exports-loader*.

```
> Any way to bi-directional passing data between vue & three ?
```

Since you will have all of your ThreeJS codes in your Vue codes, I believe you can easily call methods defined in your Vue codes as long as you have the right scope (such as binding the appropriate *"this"*).  
Or, I would prepare some states using *"Vuex"*. Vue methods dispatching some Vuex stored actions which triggers ThreeJS methods, likewise ThreeJS methods calling Vue methods to dispatch some actions...

```
> Any informations using a separated backend (like symfony or laravel) ?
```

[This project uses HtmlWebpackPlugin](https://github.com/minagawah/webpack-in-5min-vuejs/blob/master/webpack.config.common.js#L151) to dynamically create `build/index.html` out of [src/index.html](https://github.com/minagawah/webpack-in-5min-vuejs/blob/master/src/index.html). When you have your Laravel or Symphony rendered HTML page, the HTML page should refer to the built JS (with the fixed filename). So, I usually have `public` directory instread of `build`, and specify `public/js/[whatever the JS app name].js` as a build output (to which your static HTML page should refer). I have some simple projects using Laravel at work, so I will upload one of those (when I have time) as an example.

Or, I sometimes use "systemJS" to add Vue.js codes to any existing projects when the members want **NO** bundling processes (for some projects, there are designers who have absolutely no ideas about JS development procedures common nowadays, and they want their old codes to work as they are), but this is a rare case...

**Comment by minagawah** [comment]
Hi, @3kynox 
I changed the whole structure of the project.
Most important of all, as you have mentioned of the more practical use of *Vue* using major server-side framework, so did I abandoned the use of *HTML Webpack Plugin* (for dynamic HTML generation). Instead, I changed it so that the *Vue* app is basically ***embedded within static HTML files.***
0f2043af64709e487033e44ffd5c8f53ec7a4125
